GameTech/Controllers/CarrinhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameTech.Contexts;
using GameTech.Models;

namespace GameTech.Controllers
{
    public class CarrinhoController : Controller
    {
        //Instânciação de uma variável do tipo EFContext
        private EFContext db = new EFContext();


        // GET: Carrinho
        public ActionResult Index()
        {
            return View();
        }

        //GET: Comprar
        public ActionResult Comprar(int id)
        {
            //Se o valor da sessão for nulo
            if(Session["cart"] == null)
            {
                //Processo para adicionar um produto ao carrinho
                PVModel pVModel = new PVModel();
                List<Item> carrinho = new List<Item>();
                Item item = new Item();
                Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
                item.Prod_Venda = prod_Venda;
                item.Quantidade += 1;
                carrinho.Add(item);
                Session["cart"] = carrinho;
            }
            //Do contrário
            else
            {
                //Processo para aumentar a quantidade do produto
                PVModel pVModel = new PVModel();
                List<Item> carrinho = (List<Item>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    carrinho[index].Quantidade++;
                }
                else
                {
                    Item item = new Item();
                    Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
                    item.Prod_Venda = prod_Venda;
                    item.Quantidade += 1;
                    carrinho.Add(item);
                }
                Session["cart"] = carrinho;
            }
            return RedirectToAction("Index");
        }
        //GET: Remover
        public ActionResult Remover(int id)
        {
            //Procura pelo produto no carrinho pela posição no array e se achar remove o jogo do carrinho
            List<Item> carrinho = (List<Item>)Session["cart"];
            int index = isExist(id);
            carrinho.RemoveAt(index);
            Session["cart"] = carrinho;
            return RedirectToAction("Index");
        }

        //Método de verificação da existência do jogo no carrinho
        private int isExist(int id)
        {
            int i = 0;

            List<Item> carrinho = (List<Item>)Session["cart"];
            for (i=0; i < carrinho.Count; i++)
                if (carrinho[i].Prod_Venda.ProdVID.Equals(id))
                    return i;
            return -1;
        }
    }
}

GameTech/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using GameTech.Contexts;
using GameTech.Models;

namespace GameTech.Controllers
{
    public class VendaController : Controller
    {
        private EFContext db = new EFContext();

        // GET: Venda
        public ActionResult Index(string ordClass)
        {
            ViewBag.ParamClassNome = String.IsNullOrEmpty(ordClass) ? "nome_desc" : "";
            ViewBag.ParamClassPlat = ordClass == "Plataforma" ? "plat_desc" : "Plataforma";
            var prod_vendas = from p in db.Prod_Vendas
                               select p;
            switch (ordClass)
            {
                case "nome_desc":
                    prod_vendas = prod_vendas.OrderByDescending(p => p.ProdVNome);
                    break;
                case "Plataforma":
                    prod_vendas = prod_vendas.OrderBy(p => p.ProdVPlat);
                    break;
                case "plat_desc":
                    prod_vendas = prod_vendas.OrderByDescending(p => p.ProdVPlat);
                    break;
                default:
                    prod_vendas = prod_vendas.OrderBy(p => p.ProdVID);
                    break;
            }
            PVModel pVModel = new PVModel();
            ViewBag.products = pVModel.acharTodos();
            prod_vendas = db.Prod_Vendas.Include(p => p.UsuarioAtual);
            return View(db.Prod_Vendas.ToList());
        }

        // GET: Venda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
            prod_Venda.UsuarioAtual = db.Usuarios.FirstOrDefault(u => u.UsuarioId == prod_Venda.UsuAtualID);
            if (prod_Venda == null)
            {
                return HttpNotFound();
            }
            ViewBag.UsuAtualID = new SelectList(db.Usuarios, "UsuarioId", "NomeUsu", prod_Venda.UsuAtualID);
            return View(prod_Venda);
        }

        // GET: Venda/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Venda/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProdVID,ProdVNome,ProdVPlat,ProdVGen,ProdVPrec,UsuAtualID")] Prod_Venda prod_Venda)
        {
            if (ModelState.IsValid)
            {
                var identity = (ClaimsIdentity)User.Identity;
                int idLogado = int.Parse(identity.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault().Value);

                prod_Venda.UsuAtualID = idLogado;
                db.Prod_Vendas.Add(prod_Venda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(prod_Venda);
        }

        // GET: Venda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
            if (prod_Venda == null)
            {
                return HttpNotFound();
            }
            ViewBag.UsuAtualID = new SelectList(db.Usuarios, "Usuario", "NomeUsu", prod_Venda.UsuAtualID);
            return View(prod_Venda);
        }

        // POST: Venda/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProdVID,ProdVNome,ProdVPlat,ProdVGen,ProdVPrec,UsuAtualID")] Prod_Venda prod_Venda)
        {
            if (ModelState.IsValid)
            {
                var identity = (ClaimsIdentity)User.Identity;
                int idLogado = int.Parse(identity.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault().Value);
                prod_Venda.UsuAtualID = idLogado;
                db.Entry(prod_Venda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UsuAtualID = new SelectList(db.Usuarios, "Usuario", "NomeUsu", prod_Venda.UsuAtualID);
            return View(prod_Venda);
        }

        // GET: Venda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
            if (prod_Venda == null)
            {
                return HttpNotFound();
            }
            return View(prod_Venda);
        }

        // POST: Venda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
            db.Prod_Vendas.Remove(prod_Venda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult VisualizarProdutosVenda()
        {
            var identity = (ClaimsIdentity)User.Identity;
            int idLogado = int.Parse(identity.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault().Value);
            var prod_Vendas = db.Prod_Vendas.Include(p => p.UsuarioAtual);
            return View(prod_Vendas.ToList().Where(u => u.UsuAtualID == idLogado));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameTech/Views/Venda/Create.cshtml
@model GameTech.Models.Prod_Venda

@{
    ViewBag.Title = "Adicionar Venda";
}


<h2 style="color:white; background-color:black; border-style:solid; width:30%; text-align:center">Adicionar Jogo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color:white; background-color:black; border-style:solid; width:30%; margin-left:40%">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group" >
            @Html.LabelFor(model => model.ProdVNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdVNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdVNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdVPlat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProdVPlat, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("ProdVPlat", new List<SelectListItem>
                {
                    new SelectListItem{Text = "Escolha uma plataforma", Selected = true, Disabled = true},
                    new SelectListItem{Text = "Nintendo Wii U", Value = "Nintendo Wii U"},
                    new SelectListItem{Text = "Nintendo Switch", Value = "Nintendo Switch"},
                    new SelectListItem{Text = "PC", Value = "PC"},
                    new SelectListItem{Text = "Playstation 3", Value = "Playstation 3"},
                    new SelectListItem{Text = "Playstation 4", Value = "Playstation 4"},
                    new SelectListItem{Text = "Xbox 360", Value = "Xbox 360"},
                    new SelectListItem{Text = "Xbox One", Value = "Xbox One"}
                })
                @Html.ValidationMessageFor(model => model.ProdVPlat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdVGen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProdVGen, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("ProdVGen", new List<SelectListItem>
                {
                    new SelectListItem{Text = "Escolha um gênero", Selected = true, Disabled = true},
                    new SelectListItem{Text = "Ação", Value = "Ação"},
                    new SelectListItem{Text = "Aventura", Value = "Aventura"},
                    new SelectListItem{Text = "Corrida", Value = "Corrida"},
                    new SelectListItem{Text = "Estratégia", Value = "Estratégia"},
                    new SelectListItem{Text = "Esporte", Value = "Esporte"},
                    new SelectListItem{Text = "Luta", Value = "Luta"},
                    new SelectListItem{Text = "RPG", Value = "RPG"},
                    new SelectListItem{Text = "Simulação", Value = "Simulação"},
                    new SelectListItem{Text = "Tiro", Value = "Tiro"}
                })
                @Html.ValidationMessageFor(model => model.ProdVGen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdVPrec, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdVPrec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdVPrec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-dark" /> |
                @Html.ActionLink("Voltar", "Index", null, new { @class="btn btn-dark"})
            </div>
        </div>
    </div>
}

GameTech/Views/Venda/Delete.cshtml
@model GameTech.Models.Prod_Venda

@{
    ViewBag.Title = "Deletar Venda";
}


<h2 style="color:white; background-color:black; border-style:solid; width:10%; text-align:center">Deletar</h2>

<h3 style="color:white; background-color:black; border-style:solid; width:35%; margin-left:38%; text-align:center">Deseja excluir o seguinte item</h3>
<div style="color:white; background-color:black; border-style:solid; width:30%; margin-left:40%; text-align:center">
    <h4>Produto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProdVNome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdVNome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdVPlat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdVPlat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdVGen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdVGen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProdVPrec)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProdVPrec)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover produto" class="btn btn-dark" /> |
            @Html.ActionLink("Cancelar", "VisualizarProdutosVenda", null, new { @class="btn btn-dark"})
        </div>
    }
</div>

GameTech/Views/Venda/Details.cshtml
@model GameTech.Models.Prod_Venda

@{
    ViewBag.Title = "Detalhes Venda";
}


<h2 style="color:white; background-color:black; border-style:solid; width:15%; text-align:center">Detalhes</h2>

<div style="color:white; background-color:black; border-style:solid; width:30%; margin-left:40%; text-align:center">

    <div>
        <h4>Jogo</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.ProdVNome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProdVNome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProdVPlat)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProdVPlat)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProdVGen)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProdVGen)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ProdVPrec)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ProdVPrec)
            </dd>

            <dt>
                Vendedor
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UsuarioAtual.NomeUsu)
            </dd>

        </dl>
        <div>
            @Html.ActionLink("Voltar", "Index")
        </div>
    </div>
    
</div>

GameTech/Views/Venda/Edit.cshtml
@model GameTech.Models.Prod_Venda

@{
    ViewBag.Title = "Editar Venda";
}


<h2 style="color:white; background-color:black; border-style:solid; width:10%; text-align:center">Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color:white; background-color:black; border-style:solid; width:30%; margin-left:40%">
        <h4>Jogo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProdVID)

        <div class="form-group">
            @Html.LabelFor(model => model.ProdVNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdVNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdVNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdVPlat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProdVPlat, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("ProdVPlat", new List<SelectListItem>
                {
                    new SelectListItem{Text = "Escolha uma plataforma", Selected = true, Disabled = true},
                    new SelectListItem{Text = "Nintendo Wii U", Value = "Nintendo Wii U"},
                    new SelectListItem{Text = "Nintendo Switch", Value = "Nintendo Switch"},
                    new SelectListItem{Text = "PC", Value = "PC"},
                    new SelectListItem{Text = "Playstation 3", Value = "Playstation 3"},
                    new SelectListItem{Text = "Playstation 4", Value = "Playstation 4"},
                    new SelectListItem{Text = "Xbox 360", Value = "Xbox 360"},
                    new SelectListItem{Text = "Xbox One", Value = "Xbox One"}
                })
                @Html.ValidationMessageFor(model => model.ProdVPlat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdVGen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ProdVGen, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownList("ProdVGen", new List<SelectListItem>
                {
                    new SelectListItem{Text = "Escolha um gênero", Selected = true, Disabled = true},
                    new SelectListItem{Text = "Ação", Value = "Ação"},
                    new SelectListItem{Text = "Aventura", Value = "Aventura"},
                    new SelectListItem{Text = "Corrida", Value = "Corrida"},
                    new SelectListItem{Text = "Estratégia", Value = "Estratégia"},
                    new SelectListItem{Text = "Esporte", Value = "Esporte"},
                    new SelectListItem{Text = "Luta", Value = "Luta"},
                    new SelectListItem{Text = "RPG", Value = "RPG"},
                    new SelectListItem{Text = "Simulação", Value = "Simulação"},
                    new SelectListItem{Text = "Tiro", Value = "Tiro"}
                })
                @Html.ValidationMessageFor(model => model.ProdVGen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProdVPrec, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProdVPrec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProdVPrec, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar alterações" class="btn btn-dark" /> |
                @Html.ActionLink("Voltar", "VisualizarProdutosVenda", null, new { @class="btn btn-dark"})
            </div>
        </div>
    </div>
}

GameTech/Views/Venda/Index.cshtml
@model IEnumerable<GameTech.Models.Prod_Venda>
@using System.Security.Claims;
@{
    ViewBag.Title = "Venda";
}


<style>

    * {
        margin: 0;
        padding: 0;
    }

    .menu {
        width: 100%;
        height: 55px;
        background-color: black;
    }

        .menu ul {
            list-style: none;
            position: relative;
        }

            .menu ul li {
                width: 150px;
                float: left;
            }

        .menu a {
            padding: 15px;
            display: block;
            text-decoration: none;
            text-align: center;
            background-color: black;
            color: white;
        }

        .menu ul ul {
            position: absolute;
            visibility: hidden;
        }

        .menu ul li:hover ul {
            visibility: visible;
        }

        .menu a:hover {
            background-color: white;
            color: black;
        }

        .menu ul ul li {
            float: none;
            border-bottom: solid 1px black
        }
</style>

<h2 style="color:white; background-color:black; border-style:solid; width:10%; text-align:center">Venda</h2>

<nav class="menu">
    <ul>
        <li><a href="~/Home/Index">Home</a></li>
        <li><a href="~/Troca/Index">Troca</a></li>
        <li><a href="~/Locacao/Index">Locação</a></li>
    </ul>
</nav>

<p>

</p>

<p>
    @Html.ActionLink("Adicionar produto", "Create", null, new { @class = "btn btn-dark" }) |
    @Html.ActionLink("Vizualizar Produtos", "VisualizarProdutosVenda", null, new { @class = "btn btn-dark" })
</p>
<table class="table" style="color:white; background-color:black; border-style:solid">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProdVNome)
            @*@Html.ActionLink("Nome", "Index", new { ordClass = ViewBag.ParamClassNome })*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdVPlat)
            @*@Html.ActionLink("Plataforma", "Index", new { ordClass = ViewBag.ParamClassPlat })*@
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdVGen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdVPrec)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProdVNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProdVPlat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProdVGen)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProdVPrec)
            </td>
            <td>
                @Html.ActionLink("Detalhes", "Details", new { id = item.ProdVID }) |
                @{
                    var identity = (ClaimsIdentity)User.Identity;
                    int idLogado = int.Parse(identity.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault().Value);

                    if (item.UsuAtualID != idLogado)
                    {
                        @Html.ActionLink("Comprar Agora", "Comprar", "Carrinho", new { id = item.ProdVID }, null)
                    }
                }
                

            </td>
        </tr>
    }

</table>

GameTech/Views/Venda/VisualizarProdutosVenda.cshtml
@model IEnumerable<GameTech.Models.Prod_Venda>

@{
    ViewBag.Title = "VisualizarProdutosVenda";
}

<h2 style="color:white; background-color:black; border-style:solid; width:30%; text-align:center">Visualizar meus Produtos</h2>

<p>
    @Html.ActionLink("Adicionar", "Create", null, new { @class="btn btn-dark"}) |
    @Html.ActionLink("Voltar", "Index", null, new { @class="btn btn-dark"})
</p>
<table class="table" style="color:white; background-color:black; border-style:solid">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.ProdVNome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdVPlat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdVGen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProdVPrec)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.ProdVNome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdVPlat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdVGen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProdVPrec)
        </td>
        <td>
            @Html.ActionLink("Alterar", "Edit", new { id=item.ProdVID }) |
            @Html.ActionLink("Remover", "Delete", new { id=item.ProdVID })
        </td>
    </tr>
}

</table>