GameTech/Controllers/CarrinhoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameTech.Contexts;
using GameTech.Models;

namespace GameTech.Controllers
{
    public class CarrinhoController : Controller
    {
        //Instânciação de uma variável do tipo EFContext
        private EFContext db = new EFContext();


        // GET: Carrinho
        public ActionResult Index()
        {
            return View();
        }

        //GET: Comprar
        public ActionResult Comprar(int id)
        {
            //Se o valor da sessão for nulo
            if(Session["cart"] == null)
            {
                //Processo para adicionar um produto ao carrinho
                PVModel pVModel = new PVModel();
                List<Item> carrinho = new List<Item>();
                Item item = new Item();
                Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
                item.Prod_Venda = prod_Venda;
                item.Quantidade += 1;
                carrinho.Add(item);
                Session["cart"] = carrinho;
            }
            //Do contrário
            else
            {
                //Processo para aumentar a quantidade do produto
                PVModel pVModel = new PVModel();
                List<Item> carrinho = (List<Item>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    carrinho[index].Quantidade++;
                }
                else
                {
                    Item item = new Item();
                    Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
                    item.Prod_Venda = prod_Venda;
                    item.Quantidade += 1;
                    carrinho.Add(item);
                }
                Session["cart"] = carrinho;
            }
            return RedirectToAction("Index");
        }
        //GET: Remover
        public ActionResult Remover(int id)
        {
            //Procura pelo produto no carrinho pela posição no array e se achar remove o jogo do carrinho
            List<Item> carrinho = (List<Item>)Session["cart"];
            int index = isExist(id);
            carrinho.RemoveAt(index);
            Session["cart"] = carrinho;
            return RedirectToAction("Index");
        }

        //Método de verificação da existência do jogo no carrinho
        private int isExist(int id)
        {
            int i = 0;

            List<Item> carrinho = (List<Item>)Session["cart"];
            for (i=0; i < carrinho.Count; i++)
                if (carrinho[i].Prod_Venda.ProdVID.Equals(id))
                    return i;
            return -1;
        }
    }
}

GameTech/Controllers/VendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using GameTech.Contexts;
using GameTech.Models;

namespace GameTech.Controllers
{
    public class VendaController : Controller
    {
        private EFContext db = new EFContext();

        // GET: Venda
        public ActionResult Index(string ordClass)
        {
            ViewBag.ParamClassNome = String.IsNullOrEmpty(ordClass) ? "nome_desc" : "";
            ViewBag.ParamClassPlat = ordClass == "Plataforma" ? "plat_desc" : "Plataforma";
            var prod_vendas = from p in db.Prod_Vendas
                               select p;
            switch (ordClass)
            {
                case "nome_desc":
                    prod_vendas = prod_vendas.OrderByDescending(p => p.ProdVNome);
                    break;
                case "Plataforma":
                    prod_vendas = prod_vendas.OrderBy(p => p.ProdVPlat);
                    break;
                case "plat_desc":
                    prod_vendas = prod_vendas.OrderByDescending(p => p.ProdVPlat);
                    break;
                default:
                    prod_vendas = prod_vendas.OrderBy(p => p.ProdVID);
                    break;
            }
            PVModel pVModel = new PVModel();
            ViewBag.products = pVModel.acharTodos();
            prod_vendas = db.Prod_Vendas.Include(p => p.UsuarioAtual);
            return View(db.Prod_Vendas.ToList());
        }

        // GET: Venda/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
            prod_Venda.UsuarioAtual = db.Usuarios.FirstOrDefault(u => u.UsuarioId == prod_Venda.UsuAtualID);
            if (prod_Venda == null)
            {
                return HttpNotFound();
            }
            ViewBag.UsuAtualID = new SelectList(db.Usuarios, "UsuarioId", "NomeUsu", prod_Venda.UsuAtualID);
            return View(prod_Venda);
        }

        // GET: Venda/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Venda/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProdVID,ProdVNome,ProdVPlat,ProdVGen,ProdVPrec,UsuAtualID")] Prod_Venda prod_Venda)
        {
            if (ModelState.IsValid)
            {
                var identity = (ClaimsIdentity)User.Identity;
                int idLogado = int.Parse(identity.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault().Value);

                prod_Venda.UsuAtualID = idLogado;
                db.Prod_Vendas.Add(prod_Venda);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(prod_Venda);
        }

        // GET: Venda/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
            if (prod_Venda == null)
            {
                return HttpNotFound();
            }
            ViewBag.UsuAtualID = new SelectList(db.Usuarios, "Usuario", "NomeUsu", prod_Venda.UsuAtualID);
            return View(prod_Venda);
        }

        // POST: Venda/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProdVID,ProdVNome,ProdVPlat,ProdVGen,ProdVPrec,UsuAtualID")] Prod_Venda prod_Venda)
        {
            if (ModelState.IsValid)
            {
                var identity = (ClaimsIdentity)User.Identity;
                int idLogado = int.Parse(identity.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault().Value);
                prod_Venda.UsuAtualID = idLogado;
                db.Entry(prod_Venda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UsuAtualID = new SelectList(db.Usuarios, "Usuario", "NomeUsu", prod_Venda.UsuAtualID);
            return View(prod_Venda);
        }

        // GET: Venda/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
            if (prod_Venda == null)
            {
                return HttpNotFound();
            }
            return View(prod_Venda);
        }

        // POST: Venda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Prod_Venda prod_Venda = db.Prod_Vendas.Find(id);
            db.Prod_Vendas.Remove(prod_Venda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult VisualizarProdutosVenda()
        {
            var identity = (ClaimsIdentity)User.Identity;
            int idLogado = int.Parse(identity.Claims.Where(c => c.Type == ClaimTypes.Sid).FirstOrDefault().Value);
            var prod_Vendas = db.Prod_Vendas.Include(p => p.UsuarioAtual);
            return View(prod_Vendas.ToList().Where(u => u.UsuAtualID == idLogado));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GameTech/Views/Carrinho/Comprar.cshtml
@using GameTech.Models;
@{
    ViewBag.Title = "Comprar";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Cart</title>
</head>
<body>

    <h3>Cart Page</h3>
    <table class="table-bordered" cellpadding="2" cellspacing="2" border="1">
        <tr>
            <th>Opção</th>
            <th>Id</th>
            <th>Nome</th>
            <th>Plataforma</th>
            <th>Gênero</th>
            <th>Preço(R$)</th>
            <th>Quantidade</th>
            <th>SubTotal</th>
        </tr>

        @foreach (Item item in (List<Item>)Session["cart"])
        {
            <tr>
                <td><a href="@Url.Action("Remover", "Cart", new { id = item.Prod_Venda.ProdVID })">Remover</a></td>
                <td>@item.Prod_Venda.ProdVID</td>
                <td>@item.Prod_Venda.ProdVNome</td>
                <td>@item.Prod_Venda.ProdVPlat</td>
                <td>@item.Prod_Venda.ProdVGen</td>
                <td>@item.Prod_Venda.ProdVPrec</td>
                <td>@item.Quantidade</td>
                <td>@(item.Prod_Venda.ProdVPrec * item.Quantidade)</td>
            </tr>
        }
        <tr>
            <td align="right" colspan="5">Total</td>
            <td>
                @{
                    List<Item> cart = (List<Item>)Session["cart"];
                    var total = cart.Sum(item => item.Prod_Venda.ProdVPrec * item.Quantidade);
                }
                @total
            </td>
        </tr>
    </table>
    <br>
    <a href="@Url.Action("Index", "Home")">Continuar Comprando</a>

</body>
</html>

GameTech/Views/Carrinho/Index.cshtml
@using GameTech.Models;
@{
    ViewBag.Title = "Carrinho";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    
</head>
<body>

    <h3 style="color:white; background-color:black; border-style:solid; width:13%; text-align:center">Carrinho</h3>
    <table class="table-bordered" cellpadding="2" cellspacing="2" border="1" style="color:white; background-color:black; border-style:solid">
        <tr>
            <th>Opção</th>
            <th>Id</th>
            <th>Nome</th>
            <th>Plataforma</th>
            <th>Gênero</th>
            <th>Preço(R$)</th>
            <th>Quantidade</th>
            <th>SubTotal</th>
        </tr>

        @foreach (Item item in (List<Item>)Session["cart"])
        {
            <tr>
                <td><a href="@Url.Action("Remover", "Cart", new { id = item.Prod_Venda.ProdVID })">Remover</a></td>
                <td>@item.Prod_Venda.ProdVID</td>
                <td>@item.Prod_Venda.ProdVNome</td>
                <td>@item.Prod_Venda.ProdVPlat</td>
                <td>@item.Prod_Venda.ProdVGen</td>
                <td>@item.Prod_Venda.ProdVPrec</td>
                <td>@item.Quantidade</td>
                <td>@(item.Prod_Venda.ProdVPrec * item.Quantidade)</td>
            </tr>
        }
        <tr>
            <td align="right" colspan="5">Total</td>
            <td>
                @{
                    List<Item> cart = (List<Item>)Session["cart"];
                    var total = cart.Sum(item => item.Prod_Venda.ProdVPrec * item.Quantidade);
                }
                @total
            </td>
        </tr>
    </table>
    <br>
    <div style="color:white; background-color:black; border-style:solid; width:15%">
        <a href="@Url.Action("Index", "Venda")">Continuar Comprando</a>
    </div>

</body>
</html>